### ISSUE TITLE
how to run game in editor

### ISSUE THREAD

**Issue by marko-lazic** [Calinou/platshoot#2]
I can't figure out how to run the game.

**Comment by Calinou** [comment]
Note that this project was developed with Godot 2.0 (it can still run on Godot 2.1.x). It cannot be run using Godot 3.0 and later.

After [downloading Godot 2.1.4](https://downloads.tuxfamily.org/godotengine/2.1.4/), clone the Git repository and import the project's `engine.cfg` file using the project manager then click **Run**.

**Comment by marko-lazic** [comment]
Thank you.
